// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Room, RoomTableId } from "./tables/Room.sol";
import { State, StateTableId } from "./tables/State.sol";
import { Game, GameTableId } from "./tables/Game.sol";
import { RoomLimit, RoomLimitTableId } from "./tables/RoomLimit.sol";
