// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRoomSystem {
  function joinRoom(bytes32 roomId) external;

  function createRoom(address gameAddress, uint256 roomLimit) external;

  function startGame() external;

  function leaveRoom() external;

  function getPlayers(bytes32 roomId) external view returns (bytes32[] memory);
}
